# ╭─────────────────────────────────ImplementationGuide-fish.json──────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  https://fshschool.org/docs/sushi/configuration/#full-configuration                            │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: silth.fhir.th.extensions
canonical: https://fhir-ig.sil-th.org/th/extensions
version: 1.0.0
name: SilTHExtensions
title: SIL-TH FHIR Extension Library (STU2)
status: active
publisher:
  name: Standards and Interoperability Lab - Thailand (SIL-TH)
  url: https://www.sil-th.org
# contact:
#   - name: Bill Cod
#     telecom:
#       - system: email
#         value: cod@reef.gov
description: An extension registry which an be cited by FHIR artifacts
license: CC0-1.0
fhirVersion: 5.0.0
dependencies:
  silth.fhir.terminology.core: 0.1.2
  hl7.fhir.uv.ips: 1.1.0
parameters:
  show-inherited-invariants: false
  excludettl: true
  excludemap: true
copyrightYear: 2023+
releaseLabel: trial-use

pages:
  index.md:
    title: SIL-TH Extensions
  # files-listing.md:
  #   title: ตัวอย่าง FHIR Document ตามแฟ้ม MoPH-PC เดิม
  # profiles.md:
  #   title: รายการ Profiles
  # extensions.md:
  #   title: รายการ Extensions

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  หน้าแรก: index.html
  สารบัญ: toc.html
  เนื้อหาทั้งหมด: artifacts.html
